### ISSUE TITLE
list_subscribers runtime error - unable to sync

### ISSUE THREAD

**Issue by tundeapp** [singer-io/tap-exacttarget#24]
When syncing list_subscribers, there is a runtime error related to 'found 2 all subscribers list'

I looked into the salesforce marketing cloud instance and there is only 1 all subscribers list available.

Here is error log:

2019-02-20 14:32:17,066Z    tap - ERROR Found 2 all subscriber lists, expected one!
2019-02-20 14:32:17,066Z    tap - Traceback (most recent call last):
2019-02-20 14:32:17,066Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_exacttarget/__init__.py", line 134, in do_sync
2019-02-20 14:32:17,067Z    tap -     stream_accessor.sync()
2019-02-20 14:32:17,067Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_exacttarget/dao.py", line 66, in sync
2019-02-20 14:32:17,067Z    tap -     return self.sync_data()
2019-02-20 14:32:17,067Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_exacttarget/endpoints/list_subscribers.py", line 107, in sync_data
2019-02-20 14:32:17,067Z    tap -     all_subscribers_list = self._get_all_subscribers_list()
2019-02-20 14:32:17,067Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_exacttarget/endpoints/list_subscribers.py", line 81, in _get_all_subscribers_list
2019-02-20 14:32:17,067Z    tap -     raise RuntimeError(msg)
2019-02-20 14:32:17,067Z    tap - RuntimeError: Found 2 all subscriber lists, expected one!
2019-02-20 14:32:17,067Z    tap - ERROR Failed to sync endpoint, moving on!

**Comment by tundeapp** [comment]
The issue is related to two 'All Subscribers' list in SFMC when the API call is made, however in the UI - there is only 1 'All Subscribers' list.
