### ISSUE TITLE
TimeoutError: [WinError 10060]

### ISSUE THREAD

**Issue by prateekgurjar-mi** [singer-io/tap-exacttarget#44]
I am getting the following error when trying to discover the catalog using the discover command
tap-exacttarget -c config.json --discover > catalog.json

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

I am running this locally, when I run the command the log shows it is fetching results from data extension endpoint and after a while it does that it gives the above error

Some configuration on salesforce setup I have the following permissions 
email_read
data_extensions_read

Let me know if more information is needed

**Comment by prateekgurjar-mi** [comment]
now I am getting a different error 

CRITICAL The read operation timed out
Traceback (most recent call last):
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\prateek.gurjar\AppData\Local\Programs\Python\Python36\Scripts\tap-exacttarget.exe\__main__.py", line 7, in <module>
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\singer\utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\tap_exacttarget\__init__.py", line 156, in main
    do_discover(args)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\tap_exacttarget\__init__.py", line 68, in do_discover
    catalog += stream_accessor.generate_catalog()
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\tap_exacttarget\endpoints\data_extensions.py", line 136, in generate_catalog
    extensions_catalog_with_fields = self._get_fields(extensions_catalog)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\tap_exacttarget\endpoints\data_extensions.py", line 99, in _get_fields
    for field in result:
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\tap_exacttarget\client.py", line 164, in request_from_cursor
    response = tap_exacttarget__getMoreResults(cursor, batch_size=batch_size)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\tap_exacttarget\fuel_overrides.py", line 32, in tap_exacttarget__getMoreResults
    obj = TapExacttarget__ET_Continue(cursor.auth_stub, cursor.last_request_id, batch_size)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\tap_exacttarget\fuel_overrides.py", line 26, in __init__
    response = auth_stub.soap_client.service.Retrieve(ws_continueRequest)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\suds\client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\suds\client.py", line 581, in invoke
    result = self.send(soapenv)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\suds\client.py", line 613, in send
    reply = self.options.transport.send(request)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\suds\transport\https.py", line 66, in send
    return HttpTransport.send(self, request)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\suds\transport\http.py", line 82, in send
    fp = self.u2open(u2request)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\site-packages\suds\transport\http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "c:\users\prateek.gurjar\appdata\local\programs\python\python36\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

**Comment by valedd** [comment]
I have the same error  #prateekgurjar-mi 



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\spotdl.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\spotdl\__main__.py", line 112, in console_entry_point
    downloader.download_multiple_songs(songObjList)
  File "c:\python38\lib\site-packages\spotdl\download\downloader.py", line 93, in download_multiple_songs
    self._download_asynchronously(songObjList)
  File "c:\python38\lib\site-packages\spotdl\download\downloader.py", line 355, in _download_asynchronously
    self.loop.run_until_complete(asyncio.gather(*tasks))
  File "c:\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\python38\lib\site-packages\spotdl\download\downloader.py", line 350, in _pool_download
    return await self.download_song(song_obj)
  File "c:\python38\lib\site-packages\spotdl\download\downloader.py", line 176, in download_song
    youtubeHandler = YouTube(
  File "c:\python38\lib\site-packages\pytube\__main__.py", line 104, in __init__
    self.prefetch()
  File "c:\python38\lib\site-packages\pytube\__main__.py", line 202, in prefetch
    self.watch_html = request.get(url=self.watch_url)
  File "c:\python38\lib\site-packages\pytube\request.py", line 42, in get
    return _execute_request(url, headers=extra_headers).read().decode("utf-8")
  File "c:\python38\lib\site-packages\pytube\request.py", line 26, in _execute_request
    return urlopen(request)  # nosec
  File "c:\python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "c:\python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "c:\python38\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "c:\python38\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
 10%|████████▊
