### ISSUE TITLE
 ERROR list index out of range on Retrieve Subscribers call

### ISSUE THREAD

**Issue by rynmccrmck** [singer-io/tap-exacttarget#49]
Received the following error while running the tap (Stitch Platform)

> 2020-05-05 16:08:20,907Z    tap - ERROR <suds.sax.document.Document object at 0x7f292f131be0>
2020-05-05 16:08:20,907Z    tap - ERROR list index out of range
2020-05-05 16:08:20,907Z    tap - Traceback (most recent call last):
2020-05-05 16:08:20,908Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_exacttarget/__init__.py", line 136, in do_sync
2020-05-05 16:08:20,908Z    tap -     stream_accessor.sync()
2020-05-05 16:08:20,908Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_exacttarget/dao.py", line 74, in sync
2020-05-05 16:08:20,908Z    tap -     return self.sync_data()
2020-05-05 16:08:20,908Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_exacttarget/endpoints/list_subscribers.py", line 140, in sync_data
2020-05-05 16:08:20,908Z    tap -     subscriber_dao.pull_subscribers_batch(subscriber_keys)
2020-05-05 16:08:20,908Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_exacttarget/endpoints/subscribers.py", line 154, in pull_subscribers_batch
2020-05-05 16:08:20,908Z    tap -     for subscriber in stream:
2020-05-05 16:08:20,908Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_exacttarget/client.py", line 139, in request_from_cursor
2020-05-05 16:08:20,908Z    tap -     response = cursor.get()
2020-05-05 16:08:20,908Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/FuelSDK/rest.py", line 303, in get
2020-05-05 16:08:20,908Z    tap -     obj = ET_Get(self.auth_stub, self.obj_type, props, search_filter, options)
2020-05-05 16:08:20,908Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/FuelSDK/rest.py", line 150, in __init__
2020-05-05 16:08:20,909Z    tap -     for prop in describe.results[0].Properties:
2020-05-05 16:08:20,909Z    tap - IndexError: list index out of range
2020-05-05 16:08:20,909Z    tap - ERROR Failed to sync endpoint, moving on!

**Comment by rynmccrmck** [comment]
Issue resolved itself.  May have been in a strange state with some changes to exact target import tables.  Difficult to debug what happened.
